name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write # OIDC token for AWS
      
jobs:
  build:
    name: Build and upload
    runs-on: ubuntu-latest

    steps:
      - name: Build app
        run: yarn build
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ap-southeast-2
          role-to-assume: arn:aws:iam::143295493206:role/gha-ips-s3-viewer
          role-session-name: GHA@IPS=Viewer
      
      - name: Upload
        run: aws s3 sync foldername s3://bes-tamanu-ips-public/viewer/
