name: Configure AWS Credentials
  uses: aws-actions/configure-aws-credentials@v2
  with:
    aws-region: ap-southeast-2
    role-to-assume: arn:aws:iam::143295493206:role/gha-ips-s3-viewer
    role-session-name: GHA@IPS=Viewer
